import{S as v,i as n}from"./assets/vendor-5ObWk2rO.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const q="48415738-453a35c27b5ce388251d5c099",S="https://pixabay.com/api/";function h(r,t){const o=new URLSearchParams({key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t});return fetch(`${S}?${o}`).then(a=>{if(!a.ok)throw new Error(a.statusText);return a.json()})}function E(r){return r.map(({webformatURL:t,largeImageURL:o,tags:a,likes:e,views:s,comments:i,downloads:w})=>`<li class='gallery-images'>
            <a href='${o}'>
                <img 
                class='gallery-image' 
                src='${t}' 
                alt='${a.split(",").slice(0,3)}' 
                />
            </a>
        <div class='gallery-image-card js-gallery-image-card'>
            <p class='image-card-likes'><span class="card-title">Likes</span><br>${e}</p>
            <p class='image-card-views'><span class="card-title">Views</span><br>${s}</p>
            <p class='image-card-comments'><span class="card-title">Comments</span><br>${i}</p>
            <p class='image-card-downloads'><span class="card-title">Downloads</span><br>${w}</p>
        </div>
    </li>`).join("")}const p=document.getElementById("search-form"),f=document.querySelector(".gallery"),y=document.querySelector(".loader"),l=document.querySelector(".load-btn"),b=()=>{y.classList.remove("hidden")},g=()=>{y.classList.add("hidden")};g();const $=()=>{l.classList.remove("hidden")},c=()=>{l.classList.add("hidden")};c();let m="",d=1,F=15,u=0;const C=new v(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function L(r){f.insertAdjacentHTML("beforeend",E(r)),C.refresh()}l.addEventListener("click",async()=>{d+=1,l.disabled=!0,b();try{const r=await h(m,d),t=r.hits;u=r.totalHits,L(t);const o=document.querySelector(".gallery-item");if(o){const{height:a}=o.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}Math.ceil(u/F)===d&&(c(),n.show({title:"",backgroundColor:"#79fbff",messageColor:"#FFFFFF",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){n.error({position:"topRight",message:r.message})}finally{l.disabled=!1,g()}});p.addEventListener("submit",async r=>{if(r.preventDefault(),m=r.target.elements.query.value.trim(),d=1,f.innerHTML="",!m){c(),n.show({backgroundColor:"#EF4040",message:"Please enter a search query!",messageColor:"#FFFFFF",position:"topRight"});return}b();try{const t=await h(m,d);if(u=t.totalHits,t.hits.length===0){n.show({title:"",backgroundColor:"#EF4040",messageColor:"#FFFFFF",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c();return}L(t.hits),u>F?$():c()}catch(t){n.error({position:"topRight",message:t.message})}finally{g(),p.reset()}});
//# sourceMappingURL=index.js.map
